### ISSUE TITLE
Aktualizovat snímky distribucí

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/proc-linux-cz#11]
Viz https://github.com/MikkCZ/proc-linux-cz/pull/2#discussion_r192583446 a nebo rovnou #10.

**Comment by MikkCZ** [comment]
Už mám připravené virtuálky pro Fedoru, Ubuntu a Mint. openSUSE ještě trochu zlobí a nechce mi po instalaci nebootovat. Když se mi podaří nahodit všechny čtyři distribuce, udělám screenshoty, abych měl všude co nejpodobnější rozložení oken.

**Comment by covex** [comment]
Ano, taky jsem to tak kdysi delal, jenze s kazdou aktualizaci instalovat novy virtual, nebo to aktualizovat bylo unavne. Obepsal jsem tedy v te dobe zname (popularni) uzivatele vsech distribuci uvedenych na strance a pozadal je o to zda by mohli posilat vzdy aktualni screenshoty.. bohuzel to moc dlouho nefungovalo. Kdysi existovalo nejaky site, kde screenshotovani cele distribuce, vcetne instalatoru delal automat, ale jestli to jeste existuje nevim.

**Comment by MikkCZ** [comment]
Zas tak negativně bych to neviděl. Tolik se toho v GNOME nebo KDE neliší. Verze Fedory poznávám tak podle tapety na ploše, ale když ta bude na snímku neaktuální, to nikoho pálit nebude.
