### ISSUE TITLE
Vylepšit zobrazení na mobilních zařízeních s malou obrazovkou

### ISSUE THREAD

**Issue by AsciiWolf** [MikkCZ/proc-linux-cz#28]
Všiml jsem si, že text u loga distribucí je v mobilní verzi špatně pozicován, viz [tento](https://user-images.githubusercontent.com/2339930/50171920-163ec900-02f4-11e9-8808-4ddde630285f.png) snímek obrazovky.

**Comment by MikkCZ** [comment]
Díky. Mobilní verzi jsem popravdě nijak neladil, takže je vlastně s podivem, že vůbec funguje. :D Udělejme z tohoto lísteček obecně na její alespoň trochu vylepšení.
