### ISSUE TITLE
My contribution to www.linux.cz

### ISSUE THREAD

**Issue by TomasRoj** [MikkCZ/proc-linux-cz#33]
Hey,

Is there some way how to contribute to this project? I mean > writing some tutorials etc. In general, I think we can make this website better. To represent the whole czech user community here in Czech republic.

**Comment by MikkCZ** [comment]
Ahoj.

Tady můžeš klidně česky. Proč.linux.cz je jen taková malá stránka, která by měla obyčejné lidi nasměrovat k rychlému výběru distra, stažení a instalaci. Nějaké pokusy a velký komunitní portál ala AbcLinuxu.cz 2.0 dělá @snajpa. Jinak svá místa pro návody apod. mají případně české komunity jednotlivých dister.

Pokud máš nápad na vylepšení nebo doplnění tohoto webu, issues a návrhy i PR se změnami jsou vítány.

**Comment by TomasRoj** [comment]
Ok, díky. Zkusím se podívat tam :-D
