### ISSUE TITLE
Některé stránky nejsou na webu jednoduše k nalezení

### ISSUE THREAD

**Issue by Zlopez** [MikkCZ/proc-linux-cz#6]
Bylo by fajn, kdyby stránky obsahovaly i mapu stránek. 
Třeba další odkazy jsem našel v podstatě jen náhodou a přitom se tato stránka docela hodí.

**Comment by MikkCZ** [comment]
Ideální by bylo mít ty stránky snadno dosažitelné, nebo je nemít vůbec. Mapa stránek IMO není řešení za špatnou navigaci nebo irelevantní obsah. ;)

**Comment by MikkCZ** [comment]
Rozstřelil jsem to do samostatných úkolů, kde se můžeme jednotlivě postarat o každou stránku.
